"""
arange(1, 11)  生成1~11包前不包后的数字，reshape为2行5列的数组
"""

In [ ]:
import torch
src = torch.arange(1, 11).reshape((2, 5))   # shape(2, 5)
src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [ ]:
index = torch.tensor([[1, 1, 2, 0, 0]])  # 2维张量 shape(1, 5)
index

tensor([[1, 1, 2, 0, 0]])

In [ ]:
torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src)
# 将src中的所有值按照index中的索引值，写入到self中的指定的index位置

tensor([[0, 0, 0, 4, 5],
        [1, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [6]:
torch.full((2, 4), 2.).scatter_(1, torch.tensor([[2], [3]]), 1.23, reduce='multiply')

tensor([[2.0000, 2.0000, 2.4600, 2.0000],
        [2.0000, 2.0000, 2.0000, 2.4600]])

In [7]:
torch.full((2, 4), 2.).scatter_(1, torch.tensor([[2],[3]]), 1.23, reduce='add')

tensor([[2.0000, 2.0000, 3.2300, 2.0000],
        [2.0000, 2.0000, 2.0000, 3.2300]])

In [11]:
index = torch.tensor([[0, 1]])
index

tensor([[0, 1]])

In [12]:
value = 2

In [15]:
torch.zeros(3, 5).scatter_(1, index, value)

tensor([[2., 2., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])